return {
  {
    'LazyVim/LazyVim',
    opts = {
      colorscheme = function()
        require('themes').setup()
        require('statusline').setup()
      end,
      icons = {
        diagnostics = {
          Error = '',
          Warn = '',
          Hint = '',
          Info = '',
        },
        git = {
          added = ' ',
          modified = ' ',
          removed = ' ',
        },
        kinds = {
          Array = ' ',
          Boolean = ' ',
          Class = '',
          Color = '',
          Constant = '',
          Constructor = '',
          Copilot = '',
          Enum = '',
          EnumMember = '',
          Event = 'ﯓ',
          Field = '',
          File = '',
          Folder = '',
          Function = '',
          Interface = '',
          Key = '',
          Keyword = '',
          Method = '',
          Module = '',
          Namespace = '',
          Null = '',
          Number = '',
          Object = '',
          Operator = '',
          Package = '',
          Property = '',
          Reference = '',
          Snippet = '',
          String = 'ﱕ',
          Struct = '',
          Text = '',
          TypeParameter = '',
          Unit = 'ﱦ',
          Value = '',
          Variable = '',
        },
      },
    },
  },
}
