return {
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "catppuccin/nvim", enabled = false, name = "catppuccin" },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/which-key.nvim", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
  { "lewis6991/gitsigns.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "goolord/alpha-nvim", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
}
